# Generated by Django 3.2.4 on 2021-06-15 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Buyback Screen Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Buyback Price')),
            ],
            options={
                'verbose_name': 'Buyback',
                'verbose_name_plural': 'Buybacks',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Buyback Screen Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Exchange Price')),
            ],
            options={
                'verbose_name': 'Exchange Screen Model',
                'verbose_name_plural': 'Exchanges',
            },
        ),
        migrations.CreateModel(
            name='SendList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Buyback ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('tested', 'Tested'), ('complete', 'Complete')], default='pending', max_length=100, verbose_name='Status')),
                ('buyback_items', models.ManyToManyField(blank=True, to='buyback.Buyback', verbose_name='BuyBack')),
                ('exchange_items', models.ManyToManyField(blank=True, to='buyback.Exchange', verbose_name='Exchange')),
            ],
            options={
                'verbose_name': 'SendList',
                'verbose_name_plural': 'SendLists',
            },
        ),
    ]
