# Generated by Django 3.2.4 on 2021-06-15 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0003_auto_20210615_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendlist',
            name='buyback_items',
        ),
        migrations.RemoveField(
            model_name='sendlist',
            name='exchange_items',
        ),
        migrations.AddField(
            model_name='buybackitem',
            name='sendlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyback.sendlist'),
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='sendlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyback.sendlist'),
        ),
    ]
