# Generated by Django 3.2.4 on 2021-06-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0004_auto_20210615_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlist',
            name='order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
