# Generated by Django 3.2.4 on 2021-06-15 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0005_sendlist_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='sendlist',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Modified'),
        ),
    ]
