# Generated by Django 3.2.4 on 2021-06-15 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0006_auto_20210615_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendlist',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='sendlist',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Modified'),
        ),
    ]
