# Generated by Django 3.2.4 on 2021-06-16 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyback', '0007_auto_20210615_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buybackitem',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='exchangeitem',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='sendlist',
            name='user',
        ),
        migrations.AddField(
            model_name='sendlist',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendlist',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
