# Generated by Django 3.2.4 on 2021-06-25 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyback', '0008_auto_20210616_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buybackitem',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='buybackitem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='customer',
        ),
        migrations.AlterField(
            model_name='sendlist',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
    ]
